### ISSUE TITLE
求助，Code Push更新没有生效，老哥帮忙解答一下

### ISSUE THREAD

**Issue by tianfeng65** [listenzz/react-native-engineering#9]
我通过你写的文档以及官方文档，使用一个全新的RN项目配置了CodePush相关的配置，但是在测试热更新没有生效。
我是这么测试的不知道对不对：
1、使用了Staging构建Archive出来一个ipa的安装包，然后把这个包装手机上了。
2、改动了一下RN组件的代码，通过appcenter codepush release-react -a xxx命令发起一个更新，版本与部署环境都是对的。
3、然后我appcenter codepush deployment list -a去查看更新的安装情况，确实有一个用户安装上了，就像是你文档中描述的过程一样。
4、但是问题来了，我手机上的APP没有更新。
不知道是哪里出了问题，不知道我上述操作的第1步是不是不对。老哥有空帮忙看一下呗，非常感谢！

**Comment by tianfeng65** [comment]
我的第1步是不是不该自己装手机上，而是把应用上传到TestFlight呢？

**Comment by tianfeng65** [comment]
搞定了，我测试的步骤没问题，问题原因在于我使用codePush的时候没有指定codePushOptions。然后导致新的包装下载了，但是一直没安装，所以我的APP上面没有看到更新。官方文档就是codePush(APP)，没有带上参数，被官方文档坑了。😰

**Comment by narakai** [comment]
@tianfeng65 请问下，用了code push上google play或者app store的话，会不会有被拒下架的风险呢？
